config/routes.rb
Rails.application.routes.draw do
  
  resources :categories

  devise_for :users
  resources :posts do 
    resources :reviews, except: [:show, :index] # to remove unnecessary URLs
  end
  root :to => 'posts#index'
  get '/business' => 'posts#business'
  get '/politics' => 'posts#politics'
  get '/tech' => 'posts#tech'
  get '/science' => 'posts#science'
  get '/health' => 'posts#health'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/sitemap' => 'pages#sitemap.xml'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  belongs_to :category
  
  validates :headline, :source, presence: true

end

app/controllers/posts_controller.rb
#encoding: UTF-8
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :business, :politics, :tech, :science, :health, :show]
  before_action :check_user, except: [:index, :business, :politics, :tech, :science, :health, :show]

  # GET /posts
  # GET /posts.json
  def index
    @category_id = Category.find_by(id:1)
    @posts = Post.where(category: @category_id).order("created_at DESC")
=begin   
    if params[:category].blank?
      @category_id = Category.find_by(1)
      @posts = Post.where(category: @category_id).order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @posts = Post.where(category: @category_id).order("created_at DESC")
    end
=end
  end
   
  def business
    @category_id = Category.find_by(id:2)
    @posts = Post.where(category: @category_id).order("created_at DESC")
  end
  
  def politics
    @category_id = Category.find_by(id:3)
    @posts = Post.where(category: @category_id).order("created_at DESC")
  end
  
  def tech
    @category_id = Category.find_by(id:4)
    @posts = Post.where(category: @category_id).order("created_at DESC")
  end
  
  def science
    @category_id = Category.find_by(id:5)
    @posts = Post.where(category: @category_id).order("created_at DESC")
  end
  
  def health
    @category_id = Category.find_by(id:6)
    @posts = Post.where(category: @category_id).order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @reviews = Review.where(post_id: @post.id).order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'لقد تم تحديث البوست بنجاح' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'لقد تم حذف البوست بنجاح' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :headline, :description, :source, :source_url, :category_id)
    end
    
    def check_user 
      unless current_user.admin? 
       redirect_to root_url, alert: "sorry, only admins can do that!"
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_body.html.erb
	<table class="table table-condensed table-hover">
	  <thead>			
	    <tr>
	      <th class="text-center hidden-xs"></th>
				<th class="text-center hidden-xs"><h5><b>العنوان</b></h5></th>
				<th class="text-center hidden-xs"><h5><b>وصف الخبر</b></h5></th>
				<th class="text-center hidden-xs"><h5><b>المصدر</b></h5></th>
				<th class="text-center hidden-xs"></th>
				
	    </tr>
	  </thead>

	  <tbody>	
			<%= render 'body1' %>
			<%= render 'body2' %>
			<%= render 'body3' %>

	  </tbody>
	</table>

app/views/posts/_body2.html.erb
  	<tr>
				<td><h4><%= l Time.zone.today - 1.day, format: '%A ,%d %B %Y'  %></h4></td>
			</tr>				
	    <% @posts.each do |post| %>
			
			<% if post.created_at.day == (Time.zone.today - 1.day).day %>	
	      <tr>
	        <td class="col-md-3 hidden-xs"><%= link_to(image_tag(post.image, class: "img-thumbnail"), post.source_url, target: '_blank') %></td>
	        <td class="col-md-2 text-center"><h4><%= link_to(post.headline, post.source_url, target: '_blank', class: "headline-link") %></h4></td>
	        <td class="col-md-3 text-center desc-text"><h5><%= truncate(post.description, length: 200) %></h5></td>
	        <td class="col-md-2 hidden-xs text-center"><%= image_tag(post.source, class: "img-rounded") %></td>
					<td class="col-md-2 text-center">
						<% if (user_signed_in?) && (current_user.admin?) %>
					 	 <!-- Single button -->
					 	 <div class="btn-group">
					 	   <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					 	     Action <span class="caret"></span>
					 	   </button>
							 <ul class="dropdown-menu" role="menu">
								 <li><%= link_to 'تعديل', edit_post_path(post), class: 'btn btn-link' %></li>
								 <li><%= link_to 'حذف', post, method: :delete, data: { confirm: 'هل أنت متأكد؟' }, class: 'btn btn-link' %></li>
							 </ul> 
						 </div>
						<% else %>
						  <h4><%= link_to 'تعليق وتقييم', post, class: 'comment-link' %></h4>
						<% end %>
					</td>
					
	      </tr>
	    <% end %>
		<% end %>

app/views/posts/_body3.html.erb
			<tr>
				<td><h4>قبل يومين او اكثر</h4></td>
			</tr>				
	    <% @posts.each do |post| %>
			
			<% unless post.created_at.day == Time.zone.today.day || post.created_at.day == (Time.zone.today-1.day).day %>	
	      <tr>
	        <td class="col-md-3 hidden-xs"><%= link_to(image_tag(post.image, class: "img-thumbnail"), post.source_url, target: '_blank') %></td>
	        <td class="col-md-2 text-center"><h4><%= link_to(post.headline, post.source_url, target: '_blank', class: "headline-link") %></h4></td>
	        <td class="col-md-3 text-center desc-text"><h5><%= truncate(post.description, length: 200) %></h5></td>
	        <td class="col-md-2 hidden-xs text-center"><%= image_tag(post.source, class: "img-rounded") %></td>
					<td class="col-md-2 text-center">
						<% if (user_signed_in?) && (current_user.admin?) %>
					 	 <!-- Single button -->
					 	 <div class="btn-group">
					 	   <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					 	     Action <span class="caret"></span>
					 	   </button>
							 <ul class="dropdown-menu" role="menu">
								 <li><%= link_to 'تعديل', edit_post_path(post), class: 'btn btn-link' %></li>
								 <li><%= link_to 'حذف', post, method: :delete, data: { confirm: 'هل أنت متأكد؟' }, class: 'btn btn-link' %></li>
							 </ul> 
						 </div>
						<% else %>
						  <h4><%= link_to 'تعليق وتقييم', post, class: 'comment-link' %></h4>
						<% end %>
					</td>
					
	      </tr>
	    <% end %>
		<% end %>

app/views/posts/_commentB.erb
	<!--
    <div class="col-md-9">
    <% if @reviews.blank? %>
			<h3> 
		لا يوجد تعليقات، كُن أوّل من يكتب تعليقاً
		  </h3>
    <% else %>
			<table class="table">
				<thead>
					<tr>
						<th class="col-md-3"></th>
						<th class="col-md-9"></th>
					</tr>
				</thead>
				<tbody>	
					<% @reviews.each do |review| %>
					<tr>
						<td>
							<h4>
								<%= "#{review.user.first_name} #{review.user.last_name}" %>
							</h4>
							<p><%= review.created_at.strftime("%-m/%-d/%-y") %></p>
						</td>
						<td class="active">
							<%= h(review.comment).gsub(/\n/, '<br/>').html_safe %>
							<br/>
	 						<% if user_signed_in? %>
	 						  <% if (review.user == current_user) || (current_user.admin?) %>
	 						    <%= link_to "Edit", edit_post_review_path(@post, review) %> |
	 								<%= link_to "Delete", post_review_path(@post, review), method: :delete, data: {confirm: 'هل أنت متأكد؟'} %>
	 							<% end %>
	 					 <% end %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
    <% end %>	
  </div>
	-->

app/views/posts/_commentH.erb
    <!-- <%= link_to "أكتب تعليقك", new_post_review_path(@post.id), class: "btn btn-default" %> -->

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { multipart: true }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
		<%= f.label :category %>
		<%= f.text_field :category_id %>
	</div>
	
	<div class="form-group">
    <%= f.label :image %><br>
    <%= f.text_area :image, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :headline %><br>
    <%= f.text_area :headline, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :source %><br>
    <%= f.text_area :source, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :source_url %><br>
    <%= f.text_area :source_url, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/business.html.erb
<% content_for :title, 'أكسجين للأموال والأعمال' %>
<div>
<%= render 'body' %>
</div>

app/views/posts/edit.html.erb
<div>
	<h1>صفحة تعدل البوست</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @post, class: 'btn btn-link' %> |
	<%= link_to 'Back', posts_path, class: 'btn btn-link' %>
</div>

app/views/posts/health.html.erb
<% content_for :title, 'أكسجين الحياة' %>

<div>
<%= render 'body' %>
</div>

app/views/posts/index.html.erb
<%= content_for :title, 'أكسجين عربي' %>

<%= render 'body' %>
	<br>
	<% if (user_signed_in?) && (current_user.admin?) %>
	  <h3>
		<%= link_to 'بوست جديد', new_post_path %> ||
		<%= link_to 'فئة جديده', new_category_path %>
	  </h3>
	<% end %>

app/views/posts/new.html.erb
<div>
	<h1>بوست جديد</h1>
	<%= render 'form' %>
	<%= link_to 'Back', posts_path, class: 'btn btn-link' %>
<div>

app/views/posts/politics.html.erb
<% content_for :title, ' ثاني أكسيد الكربون' %>

<div>
<%= render 'body' %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>
      <%= link_to(@post.headline, @post.source_url, target: '_blank', class: 'comment-link') %> |
			<%= image_tag(@post.source, class: 'img-rounded') %>
		</h3>
		<p class="hidden-xs">
		  <%= image_tag(@post.image, width: '550px', height: '310x') %>
	  </p>
		<% 'commentH' %>

  </div>
</div>
<br/>
<br/>
<br/>
<div class="col-xs-18">
	<%= content_tag :div, '', :class => "fb-comments", "data-href" => request.original_url, "data-numposts" => "5", "data-colorscheme" => "light", "data-order-by" => "time", "data-mobile" => "auto-detected" %>
	
	<% 'commentB' %>
	
</div>
<%= link_to 'الصفحه الرئيسيه', posts_path, class: 'comment-link' %>

app/views/posts/tech.html.erb
<% content_for :title, 'أكسجين رقمي' %>

<div>
<%= render 'body' %>
</div>