config/routes.rb
Rails.application.routes.draw do
  
  resources :categories

  devise_for :users
  resources :posts do 
    resources :reviews, except: [:show, :index] # to remove unnecessary URLs
  end
  root :to => 'posts#index'
  get '/business' => 'posts#business'
  get '/politics' => 'posts#politics'
  get '/tech' => 'posts#tech'
  get '/science' => 'posts#science'
  get '/health' => 'posts#health'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/sitemap' => 'pages#sitemap.xml'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_post
  before_action :check_user
  
=begin
  def index
    @reviews = Review.all
  end

  def show
  end
  
  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.post_id = @post.id
    
    respond_to do |format|
      if @review.save
        format.html { redirect_to post_path(@post.id), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @review.update(review_params)
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @post, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    def set_review
      @review = Review.find(params[:id])
    end
=end
  
   private 
    def set_post
      @post = Post.find(params[:post_id])
    end

    def review_params
      params.require(:review).permit(:comment)
    end
    
    def check_user 
      redirect_to post_path(@post.id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div>
	<%= form_for ([@post, @review]) do |f| %>
	  <% if @review.errors.any? %>
	    <div id="error_explanation" class= "alert alert-danger alert-dismissable">
	      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

	      <ul>
	      <% @review.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="form-group">
	    <%= f.label :"نص التعليق" %><br>
	    <%= f.text_area :comment, class: "form-control" %>
	  </div>
	  <div class="form-group">
	    <%= f.submit class: "btn btn-default" %>
	  </div>
	<% end %>
</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Back', post_path(@post.id) %>

app/views/reviews/index.html.erb
<div>
	<h1>Listing reviews</h1>

	<table>
	  <thead>
	    <tr>
	      <th>Comment</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @reviews.each do |review| %>
	      <tr>
	        <td><%= review.comment %></td>
	        <td><%= link_to 'Show', review %></td>
	        <td><%= link_to 'Edit', edit_review_path(review) %></td>
	        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<br>

	<%= link_to 'New Review', '#' %>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', post_path(@post.id) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>