config/routes.rb
Rails.application.routes.draw do
  
  resources :categories

  devise_for :users
  resources :posts do 
    resources :reviews, except: [:show, :index] # to remove unnecessary URLs
  end
  root :to => 'posts#index'
  get '/business' => 'posts#business'
  get '/politics' => 'posts#politics'
  get '/tech' => 'posts#tech'
  get '/science' => 'posts#science'
  get '/health' => 'posts#health'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/sitemap' => 'pages#sitemap.xml'

end

app/views/layouts/_bootstrap.html.erb
 <!-- Latest compiled and minified JQuery -->
 <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
 	
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
	
	
	
	<!-- Social Footer, Colour Matching Icons -->
	<!-- Include Font Awesome Stylesheet in Header -->
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	<!-- // -->

app/views/layouts/_fb.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ar_AR/sdk.js#xfbml=1&appId=828792173831252&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-bottom" role="navigation">
				<div class="container">

		<div class="row">
			<div class="col-md-12"><%= link_to "من نحن", pages_about_path %>
			<%= link_to "إتصل بنا", pages_contact_path %></div>
		</div>
		<br/>
							<div class="row">
								<div class="col-md-12">
		جميع الحقوق محفوظة لموقع أكسجين عربي
			Copyright &copy; 2015 
		      </p>
				</div>
				</div>
				
		</div>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58772472-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header navbar-right">
			
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
			  <%= link_to image_tag("oxygenarabi.jpg", width: "100px"), root_path %>
				<%= link_to "أكسجين عربي", root_path, class: "navbar-brand hidden-xs" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
				<li><a href="https://twitter.com/oxygenarabi" target="_blank"><i id="social" class="fa fa-twitter-square fa-3x social-tw"></i></a></li>				
				<li><a href="https://www.facebook.com/oxygenarabi" target="_blank"><i id="social" class="fa fa-facebook-square fa-3x social-fb"></i></a></li>

				<% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name %> <b class="caret"></b></a>
						<ul class="dropdown-menu">
						  <li><%= link_to "تحديث معلومات", edit_user_registration_path %></li>
							<li><%= link_to "خروج", destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
					<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->	
	</div><!-- /.container-fluid -->
	<%= render "layouts/tabs" %>
</nav>

app/views/layouts/_tabs.html.erb
	<div class="tab">
		<ul>
			<li><%= link_to "هواء نقي", "/", class: "#{cp(root_path)}" %></li>
			<li><%= link_to "إقتصاد وأعمال", business_path, class: "#{cp(business_path)}" %></li>
			<li><%= link_to "سياسة وقضايا", politics_path, class: "#{cp(politics_path)}" %></li>
			<li><%= link_to "تكنولوجيا وتطبيقات", tech_path, class: "#{cp(tech_path)}" %></li>
			<li><%= link_to "علوم وتقنية", science_path, class: "#{cp(science_path)}" %></li>
			<li><%= link_to "صحة وتغذية", health_path, class: "#{cp(health_path)}" %></li>
		</ul>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
	
	  <title><%= yield(:title) %></title>
		<%= favicon_link_tag  'oxygenarabi.jpg' %>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="description" content="أكسجين عربي - موقع عربي متخصص للبحث عن أدق المعلومات والأخبار في جميع المجالات من جميع المصادر، من مبرمجين عرب لمتصفحي الأنترنت في العالم العربي">
		<meta name="keywords" content="O.Arabi, oxygenarabi.com/ www.oxygenarabi.com, أكسجين للأموال والأعمال, ثاني أكسيد الكربون, أكسجين رقمي, أوكسجين, عناصر كيميائيه وعلوم, أكسجين الحياة">
	
	<%= render "layouts/bootstrap" %>
	<meta property="fb:app_id" content="{828792173831252}">
		 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
			
	 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
	 <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
	 <%= csrf_meta_tags %>
	 
	 <%= canonical_tag -%>
</head>
<body>
	
  <%= render "layouts/fb" %>
	<%= render "layouts/header" %>
	
	<div class="container-fluid">
	    <% flash.each do |name, msg| %>
	      <% if msg.is_a?(String) %>
	        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
	          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	          <%= content_tag :div, msg, :id => "flash_#{name}" %>
	        </div>
	      <% end %>
	    <% end %>
			
	<%= yield %>
	</div>
	<%= render "layouts/footer" %>
</body>
</html>